export type Role = "VISITANTE" | "NAO_CLIENTE" | "CLIENTE" | "REPRESENTANTE" | "ADMIN" | "ADMIN_MASTER" | "ADMIN_COLABORADOR";

export type Produto = {
  id: string;
  nome: string;
  slug?: string | null;
  codigoInterno?: string | null;
  categoriaId?: string | null;
  marcaId?: string | null;
  descricaoCurta?: string | null;
  descricaoCompleta?: string | null;
  ean?: string | null;
  ncm?: string | null;
  caixaMaster?: string | null;
  imagemPrincipal?: string | null;
  imagemOriginal?: string | null;
  imagemCard?: string | null;
  imagemDetalhe?: string | null;
  imagensExtras?: string[] | null;
  preco?: number | null;
  estoque?: number | null;
  condicaoComercial?: string | null;
  prazoEntrega?: string | null;
  fichaTecnica?: string | null;
  manualPdf?: string | null;
  observacaoComercial?: string | null;
  observacaoInterna?: string | null;
  margem?: number | null;
  ca?: string | null;
  ativo?: boolean | null;
  destaque?: boolean | null;
  lancamento?: boolean | null;
  promocao?: boolean | null;
  ordem?: number | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  aplicacoesVeiculo?: ProdutoModeloVeiculoView[] | null;
  permissoesProduto?: Record<string, boolean> | null;
};

export type Categoria = { id: string; nome: string; slug?: string | null; descricao?: string | null; imagem?: string | null; ordem?: number | null; ativo?: boolean | null };
export type Marca = { id: string; nome: string; slug?: string | null; logo?: string | null; ativo?: boolean | null };
export type Aplicacao = { id: string; nome: string; slug?: string | null; tipo?: string | null; ativo?: boolean | null };
export type Montadora = { id: string; nome: string; slug?: string | null; imagem?: string | null; ativo?: boolean | null; createdAt?: string | null; updatedAt?: string | null };
export type ModeloVeiculo = { id: string; nome: string; slug?: string | null; montadoraId: string; ativo?: boolean | null; createdAt?: string | null; updatedAt?: string | null };
export type ProdutoModeloVeiculo = { id: string; produtoId: string; montadoraId: string; modeloId: string; observacaoComercial?: string | null; createdAt?: string | null; updatedAt?: string | null };
export type ProdutoModeloVeiculoView = ProdutoModeloVeiculo & { montadoraNome?: string | null; montadoraSlug?: string | null; modeloNome?: string | null; modeloSlug?: string | null };
export type Usuario = { id: string; name: string; company?: string | null; email: string; role: Role; status: "PENDING" | "ACTIVE" | "INACTIVE"; notes?: string | null; phone?: string | null; cnpj?: string | null; address?: string | null; city?: string | null; state?: string | null; registrationNotes?: string | null; approvedAt?: string | null; approvedBy?: string | null; lastLoginAt?: string | null; createdAt?: string | null; updatedAt?: string | null; authUserId?: string | null };
export type Lead = { id: string; nome: string; empresa?: string | null; telefone?: string | null; email?: string | null; cidade?: string | null; estado?: string | null; produtoId?: string | null; mensagem?: string | null; origem?: string | null; status?: string | null; createdAt?: string | null };
export type Permission = { id: string; fieldKey: string; fieldLabel: string; visibleToVisitor: boolean; visibleToNonClient: boolean; visibleToClient: boolean; visibleToRepresentative: boolean; visibleToAdmin: boolean };
export type TelemetryEvent = { id: string; eventType: string; screen?: string | null; route?: string | null; userId?: string | null; userRole?: string | null; durationMs?: number | null; success?: boolean | null; message?: string | null; metadata?: Record<string, unknown> | null; createdAt?: string | null };
export type AuditLog = { id: string; actorUserId?: string | null; actorEmail?: string | null; action: string; entityType: string; entityId?: string | null; ipAddress?: string | null; userAgent?: string | null; metadata?: Record<string, unknown> | null; createdAt?: string | null };
export type SocialLinks = { instagram: string; linkedin: string; whatsapp: string; site: string };
export type MediaSettings = { initialImage: string; homeImage: string };
export type AboutSettings = { title: string; subtitle: string; body: string };
export type CatalogAppearance = {
  version: number;
  primaryColor: string;
  accentColor: string;
  backgroundColor: string;
  surfaceColor: string;
  textColor: string;
  fontFamily: "system" | "rounded" | "serif";
  cardRadius: number;
  dockOpacity: number;
  dockHeight: number;
  dockPosition: "bottom" | "top";
  showProductCategory: boolean;
  showProductBrand: boolean;
  logoUrl: string;
  publishedAt?: string | null;
};
export type CatalogPdfRole = "VISITANTE" | "NAO_CLIENTE" | "CLIENTE" | "REPRESENTANTE";
export type CatalogPdfEntry = { url: string; generatedAt: string; role: CatalogPdfRole; productCount: number };
export type CatalogPdfSettings = Partial<Record<CatalogPdfRole, CatalogPdfEntry>>;
export type ProdutoAplicacao = { produtoId: string; aplicacaoId: string };

export type AppSettings = {
  media?: MediaSettings & { recommendations?: Record<string, string> };
  socialLinks?: SocialLinks;
  about?: AboutSettings;
  catalogPdf?: CatalogPdfSettings;
  catalogAppearanceDraft?: CatalogAppearance;
  catalogAppearance?: CatalogAppearance;
  contact?: Record<string, unknown>;
};

export type AppData = {
  produtos: Produto[];
  categorias: Categoria[];
  marcas: Marca[];
  aplicacoes: Aplicacao[];
  montadoras: Montadora[];
  modelosVeiculo: ModeloVeiculo[];
  produtoModelosVeiculo: ProdutoModeloVeiculo[];
  usuarios: Usuario[];
  leads: Lead[];
  permissoes: Permission[];
  produtoAplicacoes: ProdutoAplicacao[];
  settings: AppSettings;
  telemetry: TelemetryEvent[];
  auditLogs: AuditLog[];
};
