create extension if not exists pg_net with schema extensions;

create table if not exists public."OrderNotificationDelivery" (
  id bigint generated by default as identity primary key,
  "orderId" text not null references public."SalesOrder"(id) on delete cascade,
  channel text not null check (channel in ('TELEGRAM')),
  "requestId" bigint,
  "createdAt" timestamptz not null default now(),
  unique ("orderId", channel)
);

alter table public."OrderNotificationDelivery" enable row level security;
revoke all on table public."OrderNotificationDelivery" from anon, authenticated;

create or replace function public.notify_new_sales_order_telegram()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, vault
as $$
declare
  bot_token text;
  chat_id text;
  request_id bigint;
  client_name text;
  representative_name text;
  message_text text;
begin
  if new.status <> 'SUBMITTED' or old.status is not distinct from new.status then
    return new;
  end if;

  if exists (
    select 1 from public."OrderNotificationDelivery"
    where "orderId" = new.id and channel = 'TELEGRAM'
  ) then
    return new;
  end if;

  select decrypted_secret into bot_token
  from vault.decrypted_secrets
  where name = 'telegram_briland_bot_token'
  order by created_at desc
  limit 1;

  select decrypted_secret into chat_id
  from vault.decrypted_secrets
  where name = 'telegram_briland_chat_id'
  order by created_at desc
  limit 1;

  if nullif(bot_token, '') is null or nullif(chat_id, '') is null then
    return new;
  end if;

  client_name := coalesce(new."clientSnapshot"->>'company', new."clientSnapshot"->>'name', 'Cliente não identificado');
  representative_name := coalesce(new."representativeSnapshot"->>'name', 'Representante não identificado');
  message_text := format(
    E'🔔 <b>Novo pedido Briland</b>\n\n<b>Pedido:</b> %s\n<b>Cliente:</b> %s\n<b>Representante:</b> %s\n<b>Total:</b> R$ %s\n\nAguardando análise no Admin Web.',
    lpad(new."orderNumber"::text, 6, '0'),
    replace(replace(replace(client_name, '&', '&amp;'), '<', '&lt;'), '>', '&gt;'),
    replace(replace(replace(representative_name, '&', '&amp;'), '<', '&lt;'), '>', '&gt;'),
    replace(to_char(coalesce(new.total, 0), 'FM999G999G990D00'), '.', ',')
  );

  select net.http_post(
    url := 'https://api.telegram.org/bot' || bot_token || '/sendMessage',
    headers := jsonb_build_object('Content-Type', 'application/json'),
    body := jsonb_build_object(
      'chat_id', chat_id,
      'text', message_text,
      'parse_mode', 'HTML',
      'disable_web_page_preview', true,
      'reply_markup', jsonb_build_object(
        'inline_keyboard', jsonb_build_array(
          jsonb_build_array(jsonb_build_object('text', 'Abrir pedidos', 'url', 'https://briland-app.vercel.app'))
        )
      )
    ),
    timeout_milliseconds := 8000
  ) into request_id;

  insert into public."OrderNotificationDelivery" ("orderId", channel, "requestId")
  values (new.id, 'TELEGRAM', request_id)
  on conflict ("orderId", channel) do nothing;

  return new;
exception when others then
  raise warning 'Falha ao enfileirar notificação Telegram do pedido %: %', new.id, sqlerrm;
  return new;
end;
$$;

revoke all on function public.notify_new_sales_order_telegram() from public, anon, authenticated;

drop trigger if exists "sales_order_telegram_notification" on public."SalesOrder";
create trigger "sales_order_telegram_notification"
after update of status on public."SalesOrder"
for each row execute function public.notify_new_sales_order_telegram();

comment on function public.notify_new_sales_order_telegram() is
'Envia novos pedidos ao Telegram usando telegram_briland_bot_token e telegram_briland_chat_id no Supabase Vault.';
